filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

# output.elasticsearch:
#   hosts: http://elasticsearch:9200
#   username: elastic
#   password: changeme
output.logstash:
  hosts: logstash:5044

logging.level: info
logging.to_stderr: true